/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to create a sidebar manually
// This sidebar is manually ordered to fix navigation issues.
  tutorialSidebar: [
    'index',
    'home/overview',
    'getting-started',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: 'module-1'}],
    },
    {
      type: 'category',
      label: 'Module 2: Humanoid Robot Kinematics',
      items: [{type: 'autogenerated', dirName: 'module-2'}],
    },
    {
      type: 'category',
      label: 'Module 3: Humanoid Robot Dynamics',
      items: [{type: 'autogenerated', dirName: 'module-3'}],
    },
    {
      type: 'category',
      label: 'Module 4: Humanoid Robot Control',
      items: [{type: 'autogenerated', dirName: 'module-4'}],
    },
    'hardware-lab-setup/index',
    {
        type: 'category',
        label: 'Capstone',
        items: [{type: 'autogenerated', dirName: 'capstone'}],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
    {
        type: 'category',
        label: 'Appendices',
        items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],
};

module.exports = sidebars;
